### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by yatavin** [eugene-patsiomkin/drivebc-connector-mock#3]
Hi Eugene,

I don’t have permission to push changes to your repository.
Can you give it to me?

Thanks,
Yuri

**Comment by eugene-patsiomkin** [comment]
Hi Yuri
 
the only way you can do it is through a pull request

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Thanks,
Eugene

**Comment by yatavin** [comment]
Ok. Thanks!
